### ISSUE TITLE
KT2024 Progress Tracker

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-killteam#899]
- [x] Scout Squad - @mal20k 
- [x] Corsair Voidscarred - @mal20k 
- [x] Exaction Squad - @mal20k 
- [x] Gellerpox Infected - @Mad-Spy 
- [x] Inquisitorial Agents - @Mad-Spy 
- [x] Hearthkyn Salvagers - @Mad-Spy 
- [x] Novitiates - @Mad-Spy 
- [x] Imperial Navy Breachers - @mal20k 
- [x] Void-dancer Troupe - @Mad-Spy 
- [x] Kasrkin - @Mad-Spy 
- [x] Hand of the Archon - @Mad-Spy 
- [x] Hernkyn Yaegirs - @Mad-Spy 
- [x] Blooded - @mal20k 
- [x] Wyrmblade - @mal20k 
- [x] Mandrakes - @mal20k 
- [x] Angels of Death - @mal20k 
- [x] Pathfinders - @mhelvin505 
- [x] Fellgor Ravagers - @Mad-Spy 
- [x] Nemesis Claw - @Mad-Spy 
- [x] Warpcoven - @mal20k 
- [x] Blades of Khaine - @Mad-Spy 
- [x] Death Korps - @mal20k 
- [x] Elucidian Starstriders - @Mad-Spy 
- [x] Kommandos - @mal20k 
- [x] Brood Brothers - @mal20k 
- [x] Farstalker Kinband - @mal20k 
- [x] Phobos Strike Team - @mal20k 
- [x] Hunter Clade - @mhelvin505 
- [x] Legionaries - @mal20k 
- [x] Chaos Cult - @mal20k 
- [x] Hierotek Circle - @mhelvin505 
- [x] Tempestus Aquilons - @mal20k 
- [x] Vespid Stingwings - @mal20k

**Comment by mal20k** [comment]
Merged with https://github.com/BSData/wh40k-killteam/pull/906
